spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/studydb
    username: studyms_user
    password: studyms_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true